In [11]:
import re

## Testing single patterns

In [12]:
text = open("dates.txt", "r").read()

In [13]:
pat_1 = r'\b(?:0[1-9]|1[0-2])/(?:0[1-9]|[12]\d|3[01])/(?:\d{2})?\d{2,4}\b'

dat_1 = re.findall(pat_1, text)

#'Janaury 1993' in dat_1

In [14]:
pat_2 = r'\b(?:\d{1,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*(?: \d{1,2}[ ,])? (?:\d{2})?\d{2,4}\b'

dat_2 = re.findall(pat_2, text)

#'Janaury 1993' in dat_2

In [15]:
pat_3 = r'\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \d{4}\b'

dat_3 = re.findall(pat_3, text)

#'24/1990' in dat_3

In [16]:
pat_4 = r'\b(?:0[1-9]|1[0-2])/\d{4}\b'

dat_4 = re.findall(pat_4, text)

#'24/1990' in dat_4

In [17]:
pat_5 = r'\b\d{4}\b'

dat_5 = re.findall(pat_5, text)

#'9/36/308' in dat_5

In [18]:
dates = dat_1 + dat_2 + dat_3 + dat_4 + dat_5

In [19]:
!pip3 install python-dateutil

Requirement already satisfied: python-dateutil in c:\users\crmso\appdata\roaming\python\python311\site-packages (2.8.2)

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\crmso\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\crmso\AppData\Local\Programs\Python\Python311\Lib\site-packages)

Requirement already satisfied: six>=1.5 in c:\users\crmso\appdata\roaming\python\python311\site-packages (from python-dateutil) (1.16.0)

In [20]:
from dateutil import parser

parsed_dates = []

for date_str in dates:
    parsed_date = parser.parse(date_str, fuzzy=True)
    parsed_dates.append(parsed_date.strftime("%Y-%m-%d"))
    print(parsed_date.strftime("%Y-%m-%d"))

1993-03-25
1989-10-24
1976-10-13
1979-10-21
1984-07-25
1986-10-24
1985-03-31
1991-06-20
1994-06-12
1975-11-22
1986-12-26
1987-10-11
1973-12-01
1982-08-20
1992-02-22
1994-07-29
1978-08-11
1991-10-29
1981-09-19
1999-01-05
1998-10-04
2000-09-14
1995-10-13
2004-04-08
1990-12-08
1997-10-05
2002-07-18
1982-10-16
1992-12-15
1987-12-04
1992-07-17
1998-12-22
1996-10-02
1990-11-05
2001-01-24
2004-09-10
1982-05-26
2002-06-28
1972-05-06
1987-10-25
1996-10-14
2007-11-30
1994-06-28
1981-01-14
1985-10-10
1985-02-11
1983-02-10
1992-02-05
2012-10-21
1995-02-14
2016-05-30
1996-01-22
1992-10-14
2003-10-06
1999-10-18
2004-11-11
2001-05-30
1978-02-02
1989-09-09
1980-03-12
1990-06-22
2015-09-28
1972-01-13
1974-03-06
1974-10-10
1974-05-26
1990-02-10
2000-08-23
2001-05-26
2007-10-21
2016-10-19
1974-03-05
1994-01-29
1978-10-21
1975-08-18
1996-11-11
1979-10-01
1986-10-13
1995-10-21
2011-01-24
1972-10-04
1993-08-23
2006-10-18
1988-12-04
1983-10-21
2010-05-26
1990-01-18
1985-06-15
1982-12-10
1988-12-09
1995-08-18
1974-06-13
2008-05-26
2002-11-11
1985-08-17
2016-10-13
2008-01-14
2004-03-12
1977-10-21
2000-08-10
1972-11-30
1993-05-06
1995-01-18
1990-04-11
2001-05-30
1994-02-18
1981-02-18
2023-01-24
1978-07-26
1999-12-23
1989-05-15
1995-09-06
1983-01-27
2023-10-23
2023-08-12
2012-09-01
1983-07-25
1989-08-11
1992-04-17
1999-07-24
1997-07-11
1981-08-14
1988-11-11
2011-06-13
1989-05-14
2023-12-14
2012-06-25
1980-10-18
1998-05-15
2023-10-14
1998-07-25
1972-06-15
1991-01-07
1985-09-25
2011-06-25
1986-05-25
2016-05-25
1977-07-25
2003-07-25
1995-05-25
1976-02-25
1995-01-25
1978-02-25
2004-05-25
2010-11-25
2012-09-25
1981-07-25
1983-05-25
1995-07-25
1993-04-25
2005-05-25
1998-12-25
2007-01-25
2016-02-25
1979-08-25
2014-10-25
2015-09-25
1976-04-25
1979-11-25
2000-02-25
1986-10-25
2002-06-25
1981-09-25
2007-06-25
1989-04-25
1999-09-25
1980-10-25
2009-12-25
1992-07-25
2008-08-25
1993-02-25
1985-04-25
1984-09-25
1986-04-25
2007-04-25
1974-09-25
2013-09-25
1985-07-25
2012-05-25
1987-01-25
2013-01-25
2010-03-25
2009-08-25
2007-09-25
2011-12-25
2004-01-25
1995-11-25
2008-09-25
1983-02-25
1983-03-25
1979-08-25
2009-01-25
1993-12-25
1974-03-25
1994-01-25
1992-12-25
2004-11-25
1977-01-25
2002-03-25
2000-02-25
2006-07-25
1994-02-25
1977-04-25
1992-10-25
1989-02-25
1978-12-25
2007-01-25
1976-06-25
2011-05-25
1978-01-25
1975-07-25
2012-11-25
1991-10-25
1973-03-25
1996-10-25
2007-06-25
1995-10-25
1999-04-25
1988-04-25
1993-12-25
1974-06-25
1986-07-25
1973-02-25
1978-03-25
2007-12-25
1980-05-25
2007-11-25
1976-03-25
2001-01-25
2004-09-25
1982-05-25
2002-06-25
1972-05-25
1987-10-25
1996-10-25
2007-11-25
1994-06-25
1981-01-25
1985-10-25
1985-02-25
1983-02-25
1992-02-25
2012-10-25
1995-02-25
2016-05-25
1996-01-25
1992-10-25
2003-10-25
1999-10-25
2004-11-25
2001-05-25
1978-02-25
1989-09-25
1980-03-25
1990-06-25
2015-09-25
1972-01-25
1974-03-25
1974-10-25
1974-05-25
1990-02-25
2000-08-25
2001-05-25
2007-10-25
2016-10-25
1974-03-25
1994-01-25
1978-10-25
1975-08-25
1996-11-25
1979-10-25
1986-10-25
1995-10-25
2011-01-25
1972-10-25
1993-08-25
2006-10-25
1988-12-25
1983-10-25
2010-05-25
1990-01-25
1985-06-25
1982-12-25
1988-12-25
1995-08-25
1974-06-25
2008-05-25
2002-11-25
1985-08-25
2016-10-25
2008-01-25
2004-03-25
1977-10-25
2000-08-25
1972-11-25
1993-05-25
1995-01-25
1985-09-25
2011-06-25
1986-05-25
2016-05-25
1977-07-25
2003-07-25
1995-05-25
1976-02-25
1995-01-25
1978-02-25
2004-05-25
2010-11-25
2012-09-25
1981-07-25
1983-05-25
1995-07-25
1993-04-25
2005-05-25
1998-12-25
2007-01-25
2016-02-25
1979-08-25
2014-10-25
2015-09-25
1976-04-25
1979-11-25
2000-02-25
1986-10-25
2002-06-25
1981-09-25
2007-06-25
1989-04-25
1999-09-25
1980-10-25
2009-12-25
1992-07-25
2008-08-25
1993-02-25
1985-04-25
1984-09-25
1986-04-25
2007-04-25
1974-09-25
2013-09-25
1985-07-25
2012-05-25
1987-01-25
2013-01-25
2010-03-25
2009-08-25
2007-09-25
2011-12-25
2004-01-25
1995-11-25
2008-09-25
1983-02-25
1983-03-25
1979-08-25
2009-01-25
1993-12-25
1974-03-25
1994-01-25
1992-12-25
2004-11-25
1977-01-25
2002-03-25
2000-02-25
2006-07-25
1994-02-25
1977-04-25
1992-10-25
1989-02-25
1978-12-25
2007-01-25
1976-06-25
2011-05-25
1978-01-25
1975-07-25
2012-11-25
1991-10-25
1973-03-25
1996-10-25
2007-06-25
1995-10-25
1999-04-25
1988-04-25
1993-12-25
1974-06-25
1986-07-25
1973-02-25
1978-03-25
2007-12-25
1980-05-25
2007-11-25
1976-03-25
2012-12-25
1987-11-25
1999-05-25
1974-07-25
1981-09-25
2004-08-25
1990-08-25
1974-11-25
2006-11-25
1973-10-25
1980-03-25
2005-12-25
1997-10-25
1993-10-25
2008-12-25
1980-10-25
1975-12-25
2010-11-25
2000-11-25
1973-06-25
1978-12-25
1975-09-25
2012-12-25
1998-11-25
1988-08-25
2001-10-25
2008-11-25
2014-12-25
1981-10-25
1986-10-25
1973-03-25
1994-12-25
2010-10-25
1994-10-25
2007-01-25
1990-03-25
2016-11-25
1986-12-25
1984-11-25
1982-11-25
1981-06-25
1978-10-25
1989-12-25
1986-11-25
2014-10-25
2004-12-25
1990-12-25
2011-12-25
1976-12-25
1984-12-25
1985-12-25
2012-12-25
1986-12-25
2002-12-25
1998-12-25
1987-12-25
2010-12-25
1982-12-25
1994-12-25
1985-12-25
1999-12-25
1974-12-25
2000-12-25
1981-12-25
2004-12-25
1990-12-25
1974-12-25
2002-12-25
2006-12-25
2011-12-25
2006-12-25
2001-12-25
2004-12-25
1982-12-25
2002-12-25
1972-12-25
1987-12-25
1996-12-25
2007-12-25
1994-12-25
1981-12-25
1985-12-25
1985-12-25
1983-12-25
1992-12-25
2012-12-25
1995-12-25
2016-12-25
1996-12-25
1992-12-25
2003-12-25
1999-12-25
2004-12-25
2001-12-25
1978-12-25
1989-12-25
1980-12-25
1990-12-25
2015-12-25
1972-12-25
1974-12-25
1974-12-25
1974-12-25
1990-12-25
2000-12-25
2001-12-25
2007-12-25
2016-12-25
1974-12-25
1994-12-25
1978-12-25
1975-12-25
1996-12-25
1979-12-25
1986-12-25
1995-12-25
2011-12-25
1972-12-25
1993-12-25
2006-12-25
1988-12-25
1983-12-25
2010-12-25
1990-12-25
1985-12-25
1982-12-25
1988-12-25
1995-12-25
1974-12-25
2008-12-25
2002-12-25
1985-12-25
2016-12-25
2008-12-25
2004-12-25
1977-12-25
2000-12-25
1972-12-25
1993-12-25
1995-12-25
1990-12-25
2001-12-25
1994-12-25
1981-12-25
2013-12-25
1986-12-25
1978-12-25
1999-12-25
1989-12-25
1995-12-25
1976-12-25
1983-12-25
1990-12-25
2004-12-25
2012-12-25
1983-12-25
1989-12-25
1992-12-25
1999-12-25
1997-12-25
1974-12-25
1981-12-25
1988-12-25
2011-12-25
1989-12-25
1975-12-25
2012-12-25
1980-12-25
1998-12-25
1974-12-25
1998-12-25
1972-12-25
1991-12-25
2011-12-25
1985-12-25
2011-12-25
1986-12-25
2016-12-25
1977-12-25
1990-12-25
2003-12-25
2015-12-25
1995-12-25
1976-12-25
1995-12-25
1978-12-25
2011-12-25
2004-12-25
2010-12-25
2012-12-25
2013-12-25
1990-12-25
1981-12-25
1983-12-25
1995-12-25
1993-12-25
2005-12-25
1998-12-25
2007-12-25
2016-12-25
1979-12-25
2014-12-25
1988-12-25
2015-12-25
1976-12-25
1979-12-25
2000-12-25
1986-12-25
2002-12-25
1981-12-25
2007-12-25
1989-12-25
1999-12-25
1980-12-25
2009-12-25
1992-12-25
2006-12-25
7787-12-25
2008-12-25
1993-12-25
2010-12-25
1985-12-25
1984-12-25
1986-12-25
2007-12-25
1974-12-25
2013-12-25
1985-12-25
2004-12-25
2012-12-25
1977-12-25
1987-12-25
1983-12-25
2013-12-25
2010-12-25
2009-12-25
2007-12-25
2011-12-25
2004-12-25
1995-12-25
2008-12-25
1983-12-25
1983-12-25
1979-12-25
2009-12-25
1993-12-25
1974-12-25
1994-12-25
1992-12-25
2004-12-25
1977-12-25
2002-12-25
2000-12-25
2004-12-25
2006-12-25
1994-12-25
1977-12-25
1992-12-25
1995-12-25
1989-12-25
1978-12-25
2007-12-25
1976-12-25
2011-12-25
1975-12-25
1978-12-25
1975-12-25
2012-12-25
1999-12-25
1991-12-25
1973-12-25
1996-12-25
2007-12-25
1995-12-25
1999-12-25
2001-12-25
2000-12-25
1988-12-25
1993-12-25
1974-12-25
1997-12-25
1986-12-25
1973-12-25
1978-12-25
2007-12-25
1998-12-25
2005-12-25
1980-12-25
2007-12-25
1976-12-25
1998-12-25
2005-12-25
1973-12-25
2005-12-25
1980-12-25
2005-12-25
1987-12-25
2004-12-25
1974-12-25
1986-12-25
1997-12-25
1993-12-25
1981-12-25
2003-12-25
1993-12-25
1983-12-25
1994-12-25
2008-12-25
1980-12-25
2003-12-25
1975-12-25
2010-12-25
1997-12-25
2014-12-25
2001-12-25
1986-12-25
1978-12-25
1975-12-25
2009-12-25
1995-12-25
1989-12-25
2000-12-25
1973-12-25
1999-12-25
2001-12-25
1978-12-25
2009-12-25
1973-12-25
2014-12-25
1975-12-25
2012-12-25
1999-12-25
1989-12-25
2009-12-25
1998-12-25
1995-12-25
2009-12-25
1988-12-25
2007-12-25
2000-12-25
2012-12-25
2001-12-25
1977-12-25
2008-12-25
1983-12-25
1979-12-25
1992-12-25
2008-12-25
2014-12-25
1974-12-25
1981-12-25
1986-12-25
1973-12-25
1994-12-25
1999-12-25
2010-12-25
1994-12-25
2007-12-25
2010-12-25
1990-12-25
2016-12-25
2004-12-25
1973-12-25
1987-12-25
2000-12-25
1975-12-25
1977-12-25
2000-12-25
1984-12-25
1973-12-25
1986-12-25
1979-12-25
2004-12-25
1984-12-25
2016-12-25
2007-12-25
1982-12-25
1981-12-25
2013-12-25
1999-12-25
2006-12-25
1978-12-25
1989-12-25
1974-12-25
1986-12-25
1983-12-25
2014-12-25
1989-12-25
1980-12-25
1992-12-25
2000-12-25
1981-12-25
2008-12-25
2002-12-25
1985-12-25
2010-12-25
2002-12-25
1994-12-25
2004-12-25
2003-12-25
1991-12-25
1982-12-25
1984-12-25
2000-12-25
2001-12-25
1982-12-25
1998-12-25
2012-12-25
1991-12-25
1988-12-25
2014-12-25
2016-12-25
1976-12-25
2011-12-25
1997-12-25
2003-12-25
1999-12-25
2010-12-25
1975-12-25
1972-12-25
2015-12-25
1989-12-25
1994-12-25
1993-12-25
1996-12-25
2013-12-25
1990-12-25
1995-12-25
2004-12-25
1987-12-25
1973-12-25
1992-12-25
1977-12-25
1985-12-25
2007-12-25
2009-12-25
1986-12-25
2002-12-25
1979-12-25
2006-12-25
2008-12-25
2005-12-25
1980-12-25

In [21]:
import pandas as pd

def parse_dates_in_text_to_df(text):
    lines = text.split('\n')
    #combined pattern
    date_pattern = r'\b(?:\d{1,2}/\d{1,2}/(?:\d{2})?\d{2,4}|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*[- ,.]? \d{1,2}(?:st|nd|rd|th)?,? \d{2,4}|(?:0[1-9]|1[0-2])/\d{4}|(?:\d{1,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*(?: \d{1,2}[ ,])? (?:\d{2})?\d{2,4})\b'
    
    parsed_dates = []
    for idx, line in enumerate(lines, start=0):
        dates_in_line = re.findall(date_pattern, line)
        for date_str in dates_in_line:
            try:
                date = parser.parse(date_str, fuzzy=True)
                parsed_dates.append((date, idx))
            except ValueError:
                pass  # Ignore errors and continue
    
    df = pd.DataFrame(parsed_dates, columns=['date', 'index'])
    return df

In [22]:
df = parse_dates_in_text_to_df(text)
len(df)

355

In [23]:
df

          date  index
0   1993-03-25      0
1   1985-06-18      1
2   2071-07-08      2
3   1975-09-27      3
4   1996-02-06      4
..         ...    ...
350 1978-10-25    434
351 1989-12-25    435
352 1986-11-25    437
353 2014-10-25    439
354 2004-12-25    451

[355 rows x 2 columns]

In [28]:
df_sorted = df.sort_values(by='date').reset_index(drop=True)

In [29]:
df_sorted

          date  index
0   1972-01-13    153
1   1972-05-06    129
2   1972-06-15    225
3   1972-10-04    171
4   1972-11-30    191
..         ...    ...
350 2071-09-12     28
351 2072-01-26     13
352 2072-05-13     98
353 2072-06-10    111
354 2072-07-20     31

[355 rows x 2 columns]